version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/book_management?sslmode=disable
    ports:
      - "8082:8082"
    depends_on:
      - db
    command: ["sh", "-c", "wait-for-it db:5432 -- ./main"]
    networks:
      - mynetwork

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: book_management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
